//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsPortal.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsPost
    {
        public decimal Id { get; set; }
        public string EnglishTitle { get; set; }
        public string OdiaTitle { get; set; }
        public string Thumbnail210 { get; set; }
        public string Thumbnail279 { get; set; }
        public string Thumbnail86 { get; set; }
        public string HeaderImageName { get; set; }
        public string EngShortDesc { get; set; }
        public string ODShortDesc { get; set; }
        public string ODContent { get; set; }
        public string SeoMeta { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Tags { get; set; }
        public Nullable<int> PostedMonth { get; set; }
        public Nullable<int> PostedYear { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string SlugUrl { get; set; }
        public Nullable<bool> IsReviewed { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ReviewedBy { get; set; }
    }
}
