//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsPortal.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchdulePostConfig
    {
        public decimal Id { get; set; }
        public Nullable<decimal> PostId { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
        public Nullable<System.DateTime> ScheduleTime { get; set; }
        public Nullable<int> TimeDelay { get; set; }
    }
}
